version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
